@echo off
title Conectando na API.
echo .............................................................
echo ................. A Tela vai iniciar ........................
echo .............................................................
echo
env\Scripts\activate && python -m scrapping
echo .............................................................
echo ................. O download vai iniciar. ...................
echo .............................................................
echo Finalizado!
pause
